# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: vimeoapi 0.1.1 ruby lib

Gem::Specification.new do |s|
  s.name = "vimeoapi"
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["\u{201c}Paulo"]
  s.date = "2015-11-19"
  s.description = "Ruby wrapper to Vimeo REST Api with some video utilities"
  s.email = "\u{201c}phsoares.ita@gmail.com\u{201d}"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/vimeo.rb",
    "lib/vimeo/base.rb",
    "lib/vimeo/exceptions.rb",
    "lib/vimeo/utils.rb",
    "test/config/secrets.yml",
    "test/files/logo.png",
    "test/files/mov_bbb.mp4",
    "test/helper.rb",
    "test/test_basic.rb",
    "vimeo.gemspec",
    "vimeoapi.gemspec"
  ]
  s.homepage = "http://github.com/paulosoares86/vimeo"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.5"
  s.summary = "Ruby wrapper to Vimeo REST Api with some video utilities"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<httparty>, ["~> 0.13.7"])
      s.add_runtime_dependency(%q<streamio-ffmpeg>, ["~> 1.0.0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<test-unit>, [">= 0"])
      s.add_development_dependency(%q<byebug>, [">= 0"])
    else
      s.add_dependency(%q<httparty>, ["~> 0.13.7"])
      s.add_dependency(%q<streamio-ffmpeg>, ["~> 1.0.0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<test-unit>, [">= 0"])
      s.add_dependency(%q<byebug>, [">= 0"])
    end
  else
    s.add_dependency(%q<httparty>, ["~> 0.13.7"])
    s.add_dependency(%q<streamio-ffmpeg>, ["~> 1.0.0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<test-unit>, [">= 0"])
    s.add_dependency(%q<byebug>, [">= 0"])
  end
end

